name: "Check & Build (with Cachix)"
on:
  workflow_dispatch: # allows manual triggering
  push:
    branches:
      - master
      - update_flake_lock_action 
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - run: |
          DEBIAN_FRONTEND=noninteractive
          sudo apt-get update -q -y && sudo apt-get install -q -y qemu-system-aarch64 qemu-efi binfmt-support qemu-user-static
      - uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: >
            experimental-features = nix-command flakes
            system-features = nixos-test benchmark big-parallel kvm recursive-nix
            extra-platforms = aarch64-linux
            keep-going = true
            substituters =
            https://aciceri-fleet.cachix.org
            https://nrdxp.cachix.org
            https://nix-community.cachix.org
            arm.cachix.org
            https://cache.nixos.org
            trusted-public-keys = >
            aciceri-fleet.cachix.org-1:WiHJIK4UFTdfvWx0lG3mCR4EddyYsRhIuMGSje3/YGI=
            nrdxp.cachix.org-1:Fc5PSqY2Jm1TrWfm88l6cvGWwz3s93c6IOifQWnhNW4=
            nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=
            arm.cachix.org-1:K3XjAeWPgWkFtSS9ge5LJSLw3xgnNqyOaG7MDecmTQ8=
            cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
      - uses: cachix/cachix-action@v10
        with:
          name: aciceri-fleet
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: sed -i 's/#\(.*\).*\#.* ga-uncomment/\1/g' flake.nix # disabling outputs unsupported inside the GitHub action
      - run: echo "hello" # nix -Lv flake check
      - run: nix -Lv build ".#nixosConfigurations.pc.config.system.build.toplevel"
      - run: nix -Lv build ".#nixosConfigurations.pbp.config.system.build.toplevel" --option system aarch64-linux
      - run: nix -Lv build ".#nixosConfigurations.hs.config.system.build.toplevel"