name: check
on:
  workflow_dispatch: # allows manual triggering
  push:
    branches:
      - master
      - update_flake_lock_action

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            max-jobs = 10

      - uses: cachix/cachix-action@v10
        with:
          name: aciceri-fleet
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - run: nix --print-build-logs --verbose flake check --allow-import-from-derivation --keep-going
